// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCMS_project.Areas.Visitors.Data;

namespace OCMS_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611132825_trackingid-is-added-to-users-entity")]
    partial class trackingidisaddedtousersentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OCMS_project.Models.Category", b =>
                {
                    b.Property<Guid>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cat_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cat_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Cat_Id = new Guid("7fbed69c-e942-456a-82bb-fdb9457dd30e"),
                            Cat_Name = "Water Leakage"
                        },
                        new
                        {
                            Cat_Id = new Guid("0e0625d6-d7f9-4c1b-b26c-e5dc239e5938"),
                            Cat_Name = "Eelectricity"
                        },
                        new
                        {
                            Cat_Id = new Guid("7a659b16-bcb1-4e9f-bc74-a7ed6e5c0cb7"),
                            Cat_Name = "Air Conditioner"
                        },
                        new
                        {
                            Cat_Id = new Guid("5d1ead8f-bb23-489e-b09a-35380986b92b"),
                            Cat_Name = "Office Kitchen"
                        });
                });

            modelBuilder.Entity("OCMS_project.Models.Complaints", b =>
                {
                    b.Property<Guid>("Complaint_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Cat_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ComplaintDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplaintImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackingId")
                        .HasColumnType("int");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Complaint_Id");

                    b.HasIndex("Cat_Id");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("OCMS_project.Models.UserCreadential", b =>
                {
                    b.Property<Guid>("CreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreadId");

                    b.ToTable("UserCreadentials");

                    b.HasData(
                        new
                        {
                            CreadId = new Guid("bf748478-12c3-44e9-bd8e-30a4637b5f2d"),
                            Password = "Admin123",
                            UserId = new Guid("6f07938b-3ceb-479a-99e7-f375bf2e84d4")
                        });
                });

            modelBuilder.Entity("OCMS_project.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("b9040149-6ee0-4492-93b6-aad8d512da52"),
                            UserId = new Guid("6f07938b-3ceb-479a-99e7-f375bf2e84d4"),
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("OCMS_project.Models.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackingId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6f07938b-3ceb-479a-99e7-f375bf2e84d4"),
                            AccountStatus = 0,
                            Email = "Admin@gmail.com",
                            FullName = "Admin",
                            Password = "Admin@123",
                            TrackingId = 0,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("OCMS_project.Models.Complaints", b =>
                {
                    b.HasOne("OCMS_project.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Cat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
